FROM scratch &&
RUN apt update && apt install -y nginx && apt install -y unzip
COPY * /var/www/html/
WORKDIR /var/www/html
RUN unzip Archive.zip
CMD [/usr/sbin/nginx, -g, daemon off;]
EXPOSE 80
FROM scratch &&
RUN apt update && apt install -y nginx && apt install -y unzip
COPY * /var/www/html/
WORKDIR /var/www/html
RUN unzip Archive.zip
CMD [/usr/sbin/nginx, -g, daemon off;]
EXPOSE 80
FROM scratch &&
RUN apt update && apt install -y nginx && apt install -y unzip
COPY * /var/www/html/
WORKDIR /var/www/html
RUN unzip Archive.zip
CMD [/usr/sbin/nginx, -g, daemon off;]
EXPOSE 80
FROM ubuntu-latest &&
RUN apt update && apt install -y nginx && apt install -y unzip
COPY * /var/www/html/
WORKDIR /var/www/html
RUN unzip Archive.zip
CMD [/usr/sbin/nginx, -g, daemon off;]
EXPOSE 80
FROM ubuntu-latest &&
RUN apt update && apt install -y nginx && apt install -y unzip
COPY * /var/www/html/
WORKDIR /var/www/html
RUN unzip Archive.zip
CMD [/usr/sbin/nginx, -g, daemon off;]
EXPOSE 80
